# Generated by Django 3.2 on 2021-05-14 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20210514_1154'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='first_time',
            new_name='created_on',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='last_updated',
            new_name='updated_on',
        ),
    ]
