# Generated by Django 3.2 on 2021-06-18 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_alter_post_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='total_views',
            field=models.IntegerField(default=0),
        ),
    ]
